[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.15",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["pp*", "cp36-*", "cp37-*", "cp38-*", "*-win32", "*-manylinux_i686"]
